In [63]:
import numpy as np

# 跑道线端点坐标
P_W = np.array([-100, 0, 0]).T

# 飞机位置和姿态角
P_B_W = np.array([0, -1000, 600])
attitude = np.array([0, 0, 0])

# 图像分辨率
image_resolution = (1000, 1000)

# 内参矩阵
K = np.array([[2000, 0, 500],
              [0, 2000, 500],
              [0, 0, 1]])

K_ = K * 1.01
K_[2,2] = 1

# 畸变参数
distortion_coeffs = np.array([0.002, 0.001, 0.001, 0.002, 0.001])

# 外参
R = np.array([[1, 0, 0],
              [0, 0, -1],
              [0, 1, 0]])
t = np.array([0, 200, 1000]).T

P_C = (R@P_W + t)
P = (K @ P_C / P_C[2])

print(P)

a = (K - K_) @ P_C / P_C[2] 
print(a)

# 外参误差

theta = 1  # 1度
cos_theta = np.cos(np.radians(theta))
sin_theta = np.sin(np.radians(theta))

R_ = np.array([ [cos_theta, -sin_theta, 0],
                [0,         0,         -1],
                [sin_theta, cos_theta,  0]])

delta_t = np.array([-1, -1, 2])

# 计算delta P
delta_P = K @ ((R_ - R) @ P_W + delta_t) / P_C[2]

print("\n外参误差下 P1在像素坐标系下的坐标:")
print(delta_P)

import numpy as np

# 畸变参数误差
delta_k = np.array([0.000001, 0.000001, 0.000001])
delta_p = np.array([0, 0])

# 坐标
x = P[0]
y = P[1]
r = np.sqrt((x-500)**2 + (y-500)**2)

print(r)

# 计算径向畸变对量测域造成的误差
delta_x = delta_k[0]*r**2 + delta_k[1]*r**4 + delta_k[2]*r**6 + 2*delta_p[0]*x*y + delta_p[1]*(r**2 + 2*x**2)
delta_y = delta_k[0]*r**2 + delta_k[1]*r**4 + delta_k[2]*r**6 + delta_p[0]*(r**2 + 2*y**2) + 2*delta_p[1]*x*y

print(f"delta x': {delta_x}")
print(f"delta y': {delta_y}")



[300. 900.   1.]
[-3. -9.  0.]

外参误差下 P1在像素坐标系下的坐标:
[-1.84215935e+00 -1.87262032e+00  2.54759356e-04]
447.21359549995793
delta x': 8000040000.199999
delta y': 8000040000.199999
